################################################################################
# Tox Configuration
################################################################################

[constants]
source_locations = streamlit_parameters

[tox]
envlist = py38, py310, format, check
skip_missing_interpreters = true

################################################################################
# PyTest
################################################################################

[testenv]
description = Tests
skip_install = true
allowlist_externals = poetry
commands_pre =
    poetry install
commands =
    poetry run pytest -s tests

################################################################################
# Flake 8
################################################################################

[testenv:format]
description = Format
skip_install = true
allowlist_externals = poetry
commands_pre =
    poetry install
commands =
    poetry run ufmt format {[constants]source_locations}

######################################################################
# Check
######################################################################

[testenv:check]
description = Formatters, Linters & Static Checkers
skip_install = true
allowlist_externals = poetry
commands_pre =
    poetry install
commands =
    poetry run flake8 {[constants]source_locations}
    poetry run ufmt check {[constants]source_locations}
    # poetry run mypy --config-file {toxinidir}/tox.ini {[constants]source_locations}

################################################################################
# Flake 8 Configuration
#
# Don't require docstrings, but parse them correctly if they are there
#   D100 - Missing docstring in public module 
#   D103 - Missing docstring in public function
#   W503 - Line break before binary operator (bug: https://github.com/mila-iqia/cookiecutter-pyml/issues/10)
################################################################################
[flake8]
max-line-length = 120
statistics = 1
ignore = D100, D103, W503
exclude =
  .tox
  .venv
  .git
  doc
  dist
